### ISSUE TITLE
ReadMe missing clear steps for install and run project

### ISSUE THREAD

**Issue by th34n1m4l** [trngl8/triangle-skeleton-demo#214]
afetr doing this

![image](https://github.com/trngl8/triangle-skeleton-demo/assets/90412781/e7a2e47e-abfb-4e61-8418-bb2e15699bb4)

I get this

![image](https://github.com/trngl8/triangle-skeleton-demo/assets/90412781/b519ed9d-e0e4-4349-8156-4c618484ac04)

So more steps are required in RedMe file

**Comment by webdewduck** [comment]
@th34n1m4l readme is ready to retest

**Comment by th34n1m4l** [comment]
@roman-duck do we need run yarn install?
Add more descriptive text for user add command (arguments and meaning missing)

**Comment by th34n1m4l** [comment]
@roman-duck not obviouse how to start/run  project. Should be mentioned in readme file too.

**Comment by webdewduck** [comment]
@th34n1m4l I have updated node and yarn instructions 
https://github.com/trngl8/triangle-skeleton-demo/pull/219
